### ISSUE TITLE
npm run start首页显示内容为空

### ISSUE THREAD

**Issue by itskaiway** [zhoulujun/wepack4-react-project-template#1]
首先非常感谢老哥的这份配置，下载之后只修改了webpack.dev.js中的getLocalIPAdress方法return 127.0.0.1，运行npm run start未见任何报错信息，但是首页一片空白，我见router中首页指向的是LoanIndexContainer这个容器，理应显示一张logo的图片和demo的单词，但是控制台没有输出任何错误信息，恕我眼拙:)看了下逻辑没有发现明显错误，Google Chrome版本为 71.0.3578.98，还请指点

**Comment by zhoulujun** [comment]
看下路由配置，在#/home

**Comment by zhoulujun** [comment]
看下路由配置，在#/home
